export const ADD_ITEM_SPENDING = 'ADD_ITEM_SPENDING'
export const ADD_ITEM_INCOME = 'ADD_ITEM_INCOME'

export const REMOVE_ITEM_SPENDING = 'REMOVE_ITEM_SPENDING'
export const REMOVE_ITEM_INCOME = 'REMOVE_ITEM_INCOME'