import { 
    REACT_NATIVE_API_KEY,
    REACT_NATIVE_APP_ID,
    REACT_NATIVE_AUTH_DOMAIN,
    REACT_NATIVE_MESSAGING_SENDER_ID,
    REACT_NATIVE_PROJECT_ID,
    REACT_NATIVE_STORAGE_BUCKET,
    REACT_NATIVE_FACEBOOK_APP_ID
} from "@env";

export default {
    REACT_NATIVE_API_KEY,
    REACT_NATIVE_APP_ID,
    REACT_NATIVE_AUTH_DOMAIN,
    REACT_NATIVE_MESSAGING_SENDER_ID,
    REACT_NATIVE_PROJECT_ID,
    REACT_NATIVE_STORAGE_BUCKET,
    REACT_NATIVE_FACEBOOK_APP_ID
}